### ISSUE TITLE
Monotype font for code blocks

### ISSUE THREAD

**Issue by maxkoryukov** [pages-themes/midnight#2]
Plz, set monotype font for code blocks, I hope, the additional notes are not required...

mattgraham/midnight#11

**Comment by benbalter** [comment]
> I hope, the additional notes are not required...

I'm afraid they are. Can you explain a bit more?

/cc @mattgraham

**Comment by maxkoryukov** [comment]
No problem;))

I am the developer :3rd_place_medal: (my wooden medal), and I spent a lot of time looking at my favorite IDE/editor (in my case - Sublime3). And there the code has a monotype-font family -- there is a reason for this, look at this pictures:

one:

![theme-before](https://cloud.githubusercontent.com/assets/8887971/21511059/939f0078-ccbd-11e6-8ca6-c07c94f52305.jpg)

two:

![theme-after](https://cloud.githubusercontent.com/assets/8887971/21511064/9b455b42-ccbd-11e6-991d-aad3ea615fc2.jpg)

----

As you could see, two strings has different visual length. But they have the same number of chars!! And on the second picture, you could see, that lines are of the same length.

Another one observation: I have migrated to the github-pages from simple `README.md` files in the repo. And github has a special formatting for the code blocks, and there the font is monotyped;)

 Summarizing:

* IDE and code-editors use monotype
* github use monotype
* monotype is convenient for the source code (IMO)

**Comment by benbalter** [comment]
Is the site you're trying to use midnight on public? I suspect you do not have the necessary Rouge syntax highlighting included. See the font and coloring on https://pages-themes.github.io/midnight/ to compare.

**Comment by maxkoryukov** [comment]
yes, I am tried to use on github-pages.

The same screenshot from https://pages-themes.github.io/midnight/ 

### Screenshot "as is"

![selection_014](https://cloud.githubusercontent.com/assets/8887971/21527777/665f3cb2-cd4f-11e6-8d0e-5accf1d49d62.jpg)

### Screenshot "changed font-family with devtools"

![selection_015](https://cloud.githubusercontent.com/assets/8887971/21527779/6af1862c-cd4f-11e6-89e2-8322a307a48d.jpg)

**Comment by benbalter** [comment]
Here's what I see when I go to that same page:

<img width="768" alt="screen shot 2016-12-28 at 1 19 22 pm" src="https://cloud.githubusercontent.com/assets/282759/21528412/4958ee3c-cd00-11e6-9940-87dc95393deb.png">

**Comment by maxkoryukov** [comment]
@benbalter I know, what is the matter: I am on Linux Mint 17, and I don't have any of this fonts (taken from scss):

`'Lucida Sans', Monaco, Bitstream Vera Sans Mono, Lucida Console, Terminal`

out of the box;)

**Comment by maxkoryukov** [comment]
Thank you!
