### ISSUE TITLE
Increase Width of Content?

### ISSUE THREAD

**Issue by nintendowii111** [pages-themes/midnight#27]
This may not be an issue but I'd like to know how to increase the width of the whole content page. I put an iframe that measures 960x720 on my website with this theme and it does not center. Using a center tag on the iframe doesnt do anything either. Thanks.

**Comment by bradipao** [comment]
I slightly increased width overriding some CSS styles. It's quite easy:
1. in your repo create file assets/css/style.scss
2. in above CSS file you will recall the standard CSS then you will override the width property (example below, copy everything, included the double --- )

```
---
---

@import "{{ site.theme }}";

.wrapper {
  max-width:800px;
  margin:0 auto;
  padding: 0 20px;
}

section {
  max-width:800px;
  padding: 0px 0px 50px 0px;
  margin: 20px 0;
  margin-top: 70px;
}
```

**Comment by nintendowii111** [comment]
> I slightly increased width overriding some CSS styles. It's quite easy:
> 
> 1. in your repo create file assets/css/style.scss
> 2. in above CSS file you will recall the standard CSS then you will override the width property (example below, copy everything, included the double --- )
> 
> ```
> ---
> ---
> 
> @import "{{ site.theme }}";
> 
> .wrapper {
>   max-width:800px;
>   margin:0 auto;
>   padding: 0 20px;
> }
> 
> section {
>   max-width:800px;
>   padding: 0px 0px 50px 0px;
>   margin: 20px 0;
>   margin-top: 70px;
> }
> ```

Thanks very much!
