### ISSUE TITLE
Wrong links to Downloads in every theme

### ISSUE THREAD

**Issue by diev** [pages-themes/midnight#4]
I have tried every online theme of presented by @pages-themes in my browser.
Every theme shows two big buttons to download `TAR` or `ZIP`.

But why do all these buttons point to `https://github.com/pages-themes/{{theme}}/{{ball}}/gh-pages` when no `gh-pages` used in theme branches now?

I look at the old sample http://mattgraham.github.com/midnight which has both `master` and `gh-pages` branches but points correctly to both downloadable balls in `master` (i.e. `https://github.com/mattgraham/midnight/zipball/master` for `ZIP`).

**Comment by diev** [comment]
I think these site variables give the wrong results for all themes now:
```
<li class="downloads"><a href="{{ site.github.zip_url }}">ZIP</a></li>
<li class="downloads"><a href="{{ site.github.tar_url }}">TAR</a></li>
```

**Comment by benbalter** [comment]
This will be fixed by https://github.com/jekyll/github-metadata/pull/85.

**Comment by holisticnetworking** [comment]
Welp. I'm not seeing any change with my page. Ideas? Thanks in advance!!

**Comment by benbalter** [comment]
@holisticnetworking are you saying that you'd like the zip and tar URL to point to the `master` branch, even if the Pages site is on `gh-pages`?

**Comment by holisticnetworking** [comment]
I'm going to confess to some ignorance. But I have a GitHub page using jekyll-theme-minimal that supports my repository, Easy Inputs:
https://holisticnetworking.github.io/easy-inputs/

The files that create that page are in the /gf-pages branch, but my understanding was that by pushing to that branch, it would update the page for the repository and the download links would therefore point to the repo's download links. Am I missing something?

**Comment by dnunes** [comment]
Same issues here. Anything we can do in the _config.yml, maybe, to solve this in the meantime?

**Comment by JW0914** [comment]
Add the following directly above the <span> for _Project Maintained By_:
```
<span class="credits right"><a class="tar_download_link" href="https://github.com/JW0914/Wikis/tarball/master">tar</a>   |   <a class="zip_download_link" href="https://github.com/JW0914/Wikis/zipball/master">zip</a></span>
```
  - Replacing `JW0914/Wikis` with the path to the root folder of the arbitrary repo
  - Which will look like: <span class="credits right"><a class="tar_download_link" href="https://github.com/JW0914/Wikis/tarball/master">tar</a>   |   <a class="zip_download_link" href="https://github.com/JW0914/Wikis/zipball/master">zip</a></span>

**Comment by diev** [comment]
This advice is to use the hard coded links instead of the proper site variables. It is a user's workaround, not a fix of this issue.

**Comment by benbalter** [comment]
There [may be a bug in some instances](https://github.com/jekyll/github-metadata/pull/110), but you should also be able to override the variable by putting the following in your site's config:

```yml
github:
  zip_url: https://example.com/foo.zip
  tar_url: https://example.com/foo.tar.gz
```

**Comment by ericmorand** [comment]
So why is this issue closed if it is not fixed?

**Comment by ppazos** [comment]
Added the config mentioned by @benbalter 

https://github.com/ppazos/cabolabs-ehrserver/blob/gh-pages/_config.yml

And the site was updated after a couple of minutes https://ppazos.github.io/cabolabs-ehrserver/

But by default the links were pointing to the same gh-pages branch, not the master branch.
